import numpy as np
import matplotlib.pyplot as plt
import h5py
import pickle
import skimage
import skimage.io
import torch
import cv2
import vigra
from tqdm.notebook import tqdm
from torch.utils.data import Dataset
from sklearn.decomposition import PCA
import splits
import matplotlib
import os
import torch
from torch.utils.data import DataLoader  # SequentialSampler

import pathlib

current_file_path = pathlib.Path(__file__).parent.absolute()


# current_file_path = os.path.abspath('')

def file_path(f):
    return os.path.join(current_file_path, 'uzh/spatial_uzh_processed/a', f)


rule download_imc:
    ouptut:
        directory(file_path('download/masks/'))
    run:
        from download_imc import download_imc
        download_imc()
