name: Building the datasets
on:
  [workflow_dispatch]
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - run: |
        conda activate ci_env
        python /data/l989o/deployed/a/tests/no_test_data.py
