name: IMC preprocess graphs
on: 
  workflow_dispatch
#  workflow_dispatch:
#   schedule:
#    - cron: '0 23 * * *'
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          python notebook_exporter.py datasets/graphs/imc_data_graphs.py ci_env
