name: IMC analyze image expression VAE
on: 
  workflow_dispatch
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          export SPATIALMUON_FLAGS="MODEL_NAME=image_expression_vae"
          python notebook_exporter.py analyses/imc/expression_vae_analysis.py ci_env
          unset SPATIALMUON_FLAGS
