name: IMC tiler
on: 
  workflow_dispatch
#  workflow_dispatch:
#   schedule:
#    - cron: '0 23 * * *'
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          conda activate ci_env
          export SPATIALMUON_NOTEBOOK="datasets/tilers/imc_data_tiler.py"
          python -m datasets.tilers.imc_data_tiler
