name: IMC preprocess data
on: 
  workflow_dispatch
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          python notebook_exporter.py datasets/imc_data.py ci_env
