name: Preprocess IMC data
on: workflow_dispatch
  schedule:
    - cron: '0 23 * * *'
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - run: |
          source ~/.bashrc
          cd /data/l989o/deployed/a
          conda activate ci_env
          python notebook_exporter.py imc_data.py
