name: Preprocess IMC data
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          conda activate ci_env
          python notebook_exporter.py imc_data.py
