name: Run tests
on:
  [push, workflow_dispatch]
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          conda activate ci_env
          python -m pytest tests/test_preprocess_data.py
          python -m pytest tests/test_data_loaders.py 
          python -m pytest tests/test_train_models.py
          conda deactivate
          conda activate scvi_env
          python -m pytest tests/test_scvi.py
