name: Run tests short
on:
  [push, workflow_dispatch]
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          
          export SPATIALMUON_SELECT_TESTS="short"
          
          conda activate ci_env
          python -m tests.setup_test_data
          conda deactivate
          
          conda activate ci_env
          python -m pytest tests/test_imc.py 
          python -m pytest tests/test_imc_jeongbin.py
          python -m pytest tests/test_visium_mousebrain.py
          conda deactivate
          
          conda activate scvi_env
          python -m pytest tests/test_scvi.py 
          conda deactivate
 
          unset SPATIALMUON_SELECT_TESTS