name: Setup env scvi
on:
  workflow_dispatch
jobs:
  test-envs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: | 
          cd tests
          bash setup_env_scvi.sh
