name: Creating the conda env
on:
  [workflow_dispatch, push] #:
#    inputs:
#      name:
#        description: 'Person to greet'
#        required: true
#        default: 'Mona the Octocat'
#      home:
#        description: 'location'
#        required: false
#        default: 'The Octoverse'

jobs:
  remove-old-conda-env:
    runs-on: self-hosted
    steps:
      - run: |
          echo "hola"