name: Visium tiler
on:
  workflow_dispatch
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          conda activate ci_env
          python notebook_exporter.py datasets/tilers/visium_data_tiler.py
