name: Visium mousebrain analyze expression VAE
on: 
  workflow_dispatch
jobs:
  test-data:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source ~/.bashrc
          python notebook_exporter.py analyses/visium_mousebrain/expression_vae_runner.py ci_env
